### ISSUE TITLE
Use local decimal point setting

### ISSUE THREAD

**Issue by jhein05** [deanishe/alfred-convert#16]
Hi,

is there a chance to make the workflow use the mac's local settings for the decimal point? While the US uses a "dot" many other countries use a "comma". Alfred's built in calculations adapt to the mac's regional settings, so it would be great if the workflow would that to, because it is confusing to use one here and the other one there. I always do it wrong the first time.

Again: Awesome extension. Thank you.
Julian

EDIT: Fixed my mistake

**Comment by deanishe** [comment]
> is there a chance to make the workflow use the mac's local settings for the decimal point? While the US uses a "comma" many other countries use a "dot".

Other way round, isn't it?

Alfred can do this because it's a native app. This workflow isn't, and your settings aren't shared with the UNIX subsystem. For example, if I set number formatting to German, `AppleLocale` is `de_GB`, which is complete nonsense (the British variety of German?)

I will look into it, but I doubt it will be possible to use your system settings (as Alfred does) without adding a native helper application. You might have to set the separators yourself in the workflow.

**Comment by jhein05** [comment]
You are absolutely right. I fixed my mixup in the original post.

Well, a setting within the workflow would certainly be good enough too. The main problem is just that I (and I am sure many others) can't just use the result from the conversion for further calculations. I always have to manually change that effing decimal point "back" into a comma :) Actually to be honest, a decimal point (full stop) makes much more sense there, than a comma. But well, it is what it is.

But now that I am thinking about it, I can just temporarily hack two dirty little transformation boxes into the workflow until you come up with something. Would be really great.

Cheers, Julian

**Comment by deanishe** [comment]
> But now that I am thinking about it, I can just temporarily hack two dirty little transformation boxes into the workflow until you come up with something.

Good thinking.

**Comment by deanishe** [comment]
[Added in v3.0](https://github.com/deanishe/alfred-convert/tree/v3.0)

Use the workflow configuration sheet in Alfred Preferences to set your separators.
