### ISSUE TITLE
Suggestion: Use exchangeratesapi.io API to convert money

### ISSUE THREAD

**Issue by JBey4you** [deanishe/alfred-convert#47]
Hi,

May I suggest you to use https://exchangeratesapi.io API? It's free, has no limit and is based on the European Central Bank's service. Users wouldn't have to create an account on openexchangerates.org to get an App ID and they could convert currencies with no limit.

**Comment by deanishe** [comment]
I actually looked at the ECB when I originally wrote the workflow, and rejected it as a source due to the very limited number of currencies it has rates for. OTOH, Yahoo! Finance was an option at that time (and is what I originally went with).

I think the request limits of Open Exchange Rates' free tier are moot in the context of your suggestion. The workflow caches the rates rather than hitting OER's API every time you do a conversion, so the number of conversions you do is irrelevant. Only the frequency with which you update rates matters. The free tier's limit of 1000 requests/month allows for hourly updates. If that's not frequently enough for you, then the ECB is certainly no good as a data source, as their rates are only updated once a day.

Using exchangeratesapi.io strikes me as pointless: The rates can easily be retrieved directly from the ECB site, and I have more confidence in the ECB's site staying up than in a free site with no apparent business model.

All that said, it *is* a PITA having to get an API key in order to perform currency conversions.

Using the ECB data by default would eliminate that: folks who need exchange rates the ECB doesn't provide would have to sign up with Open Exchange Rates, but the workflow could work "out of the box" for a lot of people (certainly, I've personally never needed a rate the ECB doesn't provide).

But I think a better solution might be to cache the OER rates in some form on my own server, eliminating the need for users to sign up for their own access.

I'll ask OER if that's acceptable.

**Comment by m-baumgartner** [comment]
> All that said, it _is_ a PITA having to get an API key in order to perform currency conversions.
> 
> Using the ECB data by default would eliminate that: folks who need exchange rates the ECB doesn't provide would have to sign up with Open Exchange Rates, but the workflow could work "out of the box" for a lot of people (certainly, I've personally never needed a rate the ECB doesn't provide).

Hey, any updates on this?
I'm presonally favorable to a simple solution based on ECB as I don't need more currencies than the ones supported there.
Maybe a good workaround for folks who DO need more currencies would be to keep the current 'openexchangerates' based solution as a fallback.

**Comment by cataclysmicvoid** [comment]
<img width="686" alt="Screen Shot 2020-02-19 at 10 24 52 PM" src="https://user-images.githubusercontent.com/31025102/74882245-a77d5580-5366-11ea-94c0-92b5f2c7d283.png">
Stumbled across this suggestion from before — and now since I can't get the api key to work with NIS currency it seems relevant again. Conversions work just fine with other currencies though! Tried a new api key to no avail.

Thanks again for great workflow.

**Comment by deanishe** [comment]
> I can't get the api key to work with NIS currency

The symbol has changed. Israeli shekel is now `ILS`
