### ISSUE TITLE
Migrate currency api to exchangeratesapi.io

### ISSUE THREAD

**Issue by kamontat** [deanishe/alfred-convert#76]
Since https://exchangeratesapi.io didn't require any API key, it will easier on user to use.

**Comment by deanishe** [comment]
Duplicate of #47.

> Migrate currency api to exchangeratesapi.io

Replacing openexchangerates.org with exchangeratesapi.io would be daft because it only supports a tiny number of exchange rates, and they're only updated once a day.

In any case, the workflow already fetches (a limited number of) exchange rates from exchangerate-api.com if no key for openexchangerates.org is set.

**Comment by jimmykl** [comment]
+1 for use of daft
